-- MySQL Script generated by MySQL Workbench
-- Wed Feb 10 19:16:26 2016
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema softacad
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema softacad
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `softacad` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `softacad` ;

-- -----------------------------------------------------
-- Table `softacad`.`blog_images`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `softacad`.`blog_images` ;

CREATE TABLE IF NOT EXISTS `softacad`.`blog_images` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  `blog_post_id` INT NULL COMMENT '',
  `image` VARCHAR(255) NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `softacad`.`categories`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `softacad`.`categories` ;

CREATE TABLE IF NOT EXISTS `softacad`.`categories` (
  `name` VARCHAR(255) NULL COMMENT '',
  `description` VARCHAR(255) NULL COMMENT '',
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `softacad`.`tours`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `softacad`.`tours` ;

CREATE TABLE IF NOT EXISTS `softacad`.`tours` (
  `name` VARCHAR(255) NULL COMMENT '',
  `image` VARCHAR(255) NULL COMMENT '',
  `category_id` INT NULL COMMENT '',
  `description` TEXT(5000) NULL COMMENT '',
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `softacad`.`blog`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `softacad`.`blog` ;

CREATE TABLE IF NOT EXISTS `softacad`.`blog` (
  `image` VARCHAR(255) NULL COMMENT '',
  `title` VARCHAR(255) NULL COMMENT '',
  `description` TEXT(5000) NULL COMMENT '',
  `created_at` DATETIME NULL COMMENT '',
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `softacad`.`tours_images`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `softacad`.`tours_images` ;

CREATE TABLE IF NOT EXISTS `softacad`.`tours_images` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  `image` VARCHAR(255) NULL COMMENT '',
  `tours_id` INT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `softacad`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `softacad`.`users` ;

CREATE TABLE IF NOT EXISTS `softacad`.`users` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  `username` VARCHAR(255) NULL COMMENT '',
  `password` VARCHAR(255) NULL COMMENT '',
  `email` VARCHAR(255) NULL COMMENT '',
  `description` VARCHAR(500) NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
